export const ACTION_TYPE = {
	SET_AUTH: 'SET_AUTH',
	RESET_AUTH: 'RESET_AUTH',
	
	SET_ACCOUNT: 'SET_ACCOUNT',
	RESET_ACCOUNT: 'RESET_ACCOUNT',

	SET_ACCOUNTS: 'SET_ACCOUNTS',
	RESET_ACCOUNTS: 'RESET_ACCOUNTS',
	ADD_ACCOUNTS: 'ADD_ACCOUNTS',

	SET_OPERATION: 'SET_OPERATION',
	RESET_OPERATION: 'RESET_OPERATION',
	
	SET_OPERATIONS: 'SET_OPERATIONS',
	RESET_OPERATIONS: 'RESET_OPERATIONS',
	ADD_OPERATIONS: 'ADD_OPERATIONS',

	SET_CATEGORY: 'SET_CATEGORY',
	RESET_CATEGORY: 'RESET_CATEGORY',
};